//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NET_E_Commerce_MVC5_ENTITY_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INVOICE()
        {
            this.INVOICEPEN = new HashSet<INVOICEPEN>();
        }
    
        public int ID { get; set; }
        public string SERIALNO { get; set; }
        public string QUEUENO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string TAX { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
        public string RECEIVER { get; set; }
        public string SENDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICEPEN> INVOICEPEN { get; set; }
    }
}
