//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NET_E_Commerce_MVC5_ENTITY_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICEPEN
    {
        public int ID { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> COUNT { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> GENERALPRICE { get; set; }
        public Nullable<int> INVOICE { get; set; }
    
        public virtual INVOICE INVOICE1 { get; set; }
    }
}
