//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NET_E_Commerce_MVC5_ENTITY_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public int ID { get; set; }
        public string SENDERMAIL { get; set; }
        public string RECEIVERMAIL { get; set; }
        public string ISSUE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
