//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NET_E_Commerce_MVC5_ENTITY_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFCommerceEntities : DbContext
    {
        public EFCommerceEntities()
            : base("name=EFCommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARI> CARI { get; set; }
        public virtual DbSet<CARILOGIN> CARILOGIN { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<EMPLOYEELOGIN> EMPLOYEELOGIN { get; set; }
        public virtual DbSet<EXPENSE> EXPENSE { get; set; }
        public virtual DbSet<INVOICE> INVOICE { get; set; }
        public virtual DbSet<INVOICEPEN> INVOICEPEN { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<SALESMOVEMENT> SALESMOVEMENT { get; set; }
        public virtual DbSet<SALESMOVEMENTLOWER> SALESMOVEMENTLOWER { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
    }
}
