//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NET_E_Commerce_MVC5_ENTITY_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.SALESMOVEMENTLOWER = new HashSet<SALESMOVEMENTLOWER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BRAND { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<decimal> BUYPRICE { get; set; }
        public Nullable<decimal> SALESPRICE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string IMAGE { get; set; }
        public Nullable<int> CATEGORY { get; set; }
    
        public virtual CATEGORY CATEGORY1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALESMOVEMENTLOWER> SALESMOVEMENTLOWER { get; set; }
    }
}
