//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NET_E_Commerce_MVC5_ENTITY_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESMOVEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALESMOVEMENT()
        {
            this.SALESMOVEMENTLOWER = new HashSet<SALESMOVEMENTLOWER>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> GENERALPRICE { get; set; }
        public Nullable<int> EMPLOYEEID { get; set; }
        public Nullable<int> CARIID { get; set; }
    
        public virtual CARI CARI { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALESMOVEMENTLOWER> SALESMOVEMENTLOWER { get; set; }
    }
}
