//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asp.NET_E_Commerce_MVC5_ENTITY_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALESMOVEMENTLOWER
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> GeneralPrice { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SalesMovementID { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SALESMOVEMENT SALESMOVEMENT { get; set; }
    }
}
